pull_request_rules:
  - name: zz-bot-approval-probe
    conditions:
      - base = main
      - label = zz-botapprove
      - "#approved-reviews-by >= 1"
    actions:
      merge:
        method: merge
